### ISSUE TITLE
Cancelling subscription.ReadLines and then calling subscription.ReadLines fails

### ISSUE THREAD

**Issue by michaelmcneilnet** [KelvinVail/Betfair#8]
My code has the following flow, which runs within a `Microsoft.Extensions.Hosting.BackgroundService` worker.

1. Read data from an external source
2. Use external data to decide market stream filters
3. Consume stream using `subscription.ReadLines(innerCancellationToken);`
4. Cancel `innerCancellationToken` after 10 minutes, so that externalData is refreshed, and subscription is updated with latest market filter.

Some pseudocode to hopefully illustrate this:

```cs
protected override async Task ExecuteAsync(CancellationToken cancellationToken)
{
  Subscription subscription;
  
  while (!cancellationToken.IsCancellationRequested)
  {
    using var innerCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
    innerCancellationTokenSource.CancelAfter(TimeSpan.FromMinutes(10));
    var innerCancellationToken = innerCancellationTokenSource.Token;
    
    var externalData = await GetExternalDataDataAsync(innerCancellationToken);
    
    subscription ??= new Subscription(credentials);
    var marketFilter = GenerateFilter(externalData);
    
    await subscription.Subscribe(marketFilter, cancellationToken: innerCancellationToken );
    
    await foreach (var message in the subscription.ReadLines(innerCancellationToken ))
    {
        // Process message
    }
  }

  subscription.Dispose()
}
```

The issue is that `Betfair.Stream.Pipeline.ReadPipeAsync` completes the reader when the cancellation token is cancelled. This means that when I try to update the filters on the existing subscription, I get the exception 

```
System.IO.IOException
  HResult=0x80131620
  Message=Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStream.<<WriteSingleChunk>g__CompleteWriteAsync|164_1>d`1.MoveNext()
   at System.Net.Security.SslStream.<WriteAsyncInternal>d__171`1.MoveNext()
   at Betfair.Stream.Pipeline.<WriteLine>d__3.MoveNext()
   at Betfair.Stream.Subscription.<Subscribe>d__11.MoveNext()
```

**Expected behavior**
I can work around this by creating a new subscription each time round my inner loop (every 10 minutes), but the Betfair docs state 

> It is possible to subscribe multiple times - each replaces the previous (each will send a new initial image and deltas) - they are not additive.

so I expected that calling 

1. subscription.Subscribe
2. subscription.ReadLines(cancellationToken)
3. _cancel token_
4. subscription.Subscribe 
5. subscription.ReadLines(cancellationToken)

would not throw an exception.

I think the `Subscription` class could reopen the pipe if it is completed and `Subscribe` or `SubscribeToOrders` is called? Another option could be to call _pipe,eader.CompleteAsync from the subscription's Dispose, rather than when ReadLines is cancelled? (I don't know enough about pipes to say whether my suggestion is good 😅)

**Version**
<PackageReference Include="Betfair" Version="8.3.4" />

**Comment by KelvinVail** [comment]
Thanks Michael. I can see how you wouldn't expect the subscription to stop working when cancelling out of the ReadLines.

Leave it with me.
